/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#799dd6",
        "surface-tint": "#3a5f94",
        "inverse-primary": "#a7c8ff",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#ebf1ff",
        "on-secondary-fixed": "#00210b",
        "surface-container-low": "#f0f3ff",
        "surface-container-high": "#dee8ff",
        "on-error": "#ffffff",
        "primary-container": "#003366",
        "background": "#f9f9ff",
        "tertiary-fixed-dim": "#c3c7cb",
        "on-secondary-container": "#007236",
        "primary-fixed": "#d5e3ff",
        "secondary-fixed-dim": "#5adf82",
        "outline": "#737780",
        "secondary-fixed": "#78fc9c",
        "tertiary": "#1a1f22",
        "tertiary-fixed": "#dfe3e7",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#a7c8ff",
        "on-secondary": "#ffffff",
        "primary": "#001e40",
        "on-secondary-fixed-variant": "#005225",
        "secondary": "#006d33",
        "tertiary-container": "#2f3437",
        "on-primary-fixed": "#001b3c",
        "on-tertiary-fixed": "#171c1f",
        "on-tertiary-fixed-variant": "#43474b",
        "on-primary": "#ffffff",
        "on-surface": "#111c2c",
        "on-primary-fixed-variant": "#1f477b",
        "surface-variant": "#d8e3fa",
        "surface-bright": "#f9f9ff",
        "outline-variant": "#c3c6d1",
        "surface": "#f9f9ff",
        "on-error-container": "#93000a",
        "on-background": "#111c2c",
        "surface-dim": "#cfdaf1",
        "on-surface-variant": "#43474f",
        "inverse-surface": "#263142",
        "surface-container": "#e7eeff",
        "on-tertiary-container": "#989ca0",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "secondary-container": "#75f999",
        "surface-container-highest": "#d8e3fa"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "lg": "24px",
        "md": "16px",
        "max-width-mobile": "480px",
        "gutter-mobile": "16px",
        "unit": "4px",
        "xs": "4px",
        "xl": "32px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Manrope", "Sarabun", "sans-serif"],
        "headline-md": ["Manrope", "Sarabun", "sans-serif"],
        "body-lg": ["Inter", "Sarabun", "sans-serif"],
        "headline-lg": ["Manrope", "Sarabun", "sans-serif"],
        "label-caps": ["Inter", "Sarabun", "sans-serif"],
        "label-bold": ["Inter", "Sarabun", "sans-serif"],
        "body-md": ["Inter", "Sarabun", "sans-serif"],
        "body-sm": ["Inter", "Sarabun", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "label-bold": ["14px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
};
